<?php
echo '<div class="container">';
echo "<div id='titcad'>Matrícula </div>";  
echo "<div id='titcad2'><label id='nome'>[var._SESSION.mat_set] - [var._SESSION.nome_comp]</label></div>";
echo "<form name='vpsaa01' action='index.php' method='get'  onSubmit='return checkEditvFields(this)'>";
echo '<div class="simpleTabs">';
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="8%" align="center">ANO</th>';
echo '<th width="8%" align="center">SEM</th>';
echo '<th width="18%" align="center">TURMA</th>';
echo '<th width="22%" align="center">MODALIDADE</th>';
echo '<th width="18%" align="center">DATA</th>';
echo '<th width="18%" align="center">STATUS</th>';
echo '<th width="9%" >AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_saa01.AA_ANO;block=tr]</font> </td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_saa01.AA_SEMESTRE]</font></td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_saa01.AA_IDTURMA]</font></td>';
echo "<td align='center'><font face='verdana' size='1'> <select  name='[blk_lista_saa01.AA_MODAL]S' disabled>".lista_modalidade()."</select><script>document.vpsaa01.[blk_lista_saa01.AA_MODAL]S.value = '[blk_lista_saa01.AA_MODAL]';</script></font> </td>";
echo "<td align='center'><font face='verdana' size='1'>[blk_lista_saa01.AA_DATA;frm='dd/mm/yyyy']</font> </td>";
echo "<td align='center'><font face='verdana' size='1'>[blk_lista_saa01.AA_SITMAT]</font> </td>";
echo '<td> <a href="?acao=Alt&idsecao=4SA&form=4SA&idsub=4&id_p_saa01=[blk_lista_saa01.AA_IDALUNO]&ano_p_saa01=[blk_lista_saa01.AA_ANO]&sem_p_saa01=[blk_lista_saa01.AA_SEMESTRE]&mod_p_saa01=[blk_lista_saa01.AA_MODAL]&tur_p_saa01=[blk_lista_saa01.AA_IDTURMA]"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href="?acao=Alt&idsecao=4SA&form=4SA&idsub=4&id_p_saa01=[blk_lista_saa01.AA_IDALUNO]&ano_p_saa01=[blk_lista_saa01.AA_ANO]&sem_p_saa01=[blk_lista_saa01.AA_SEMESTRE]&mod_p_saa01=[blk_lista_saa01.AA_MODAL]&tur_p_saa01=[blk_lista_saa01.AA_IDTURMA]"><img src="[var.dir_img]/icons/localizar.gif" ALT="Visualizar" TITLE="Visualizar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p_saa01=[blk_lista_saa01.AA_FILIAL]&id_p_saa01=[blk_lista_saa01.AA_IDALUNO]&ano_p_saa01=[blk_lista_saa01.AA_ANO]&sem_p_saa01=[blk_lista_saa01.AA_SEMESTRE]&mod_p_saa01=[blk_lista_saa01.AA_MODAL]&tur_p_saa01=[blk_lista_saa01.AA_IDTURMA]&idsecao=4SA&form=[var.form]")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '</td>';
echo '</tbody></tr>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.id_set]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.id_set]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.id_set]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.id_set]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.id_set]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table>';
echo "<tr><td><form  onSubmit='return checkEditvFields(this)'><input name='voltar' id='button'type='button' onClick='javascript:history.back();' value='Voltar'></td>
<td width='16'><img src='[var.dir_img]/icons/Add_16.png' ALT='Novo cadastro' align='LEFT'></td><td width='183'><a href='?form=4SI'>Nova matrícula</a></td></tr>";
echo '</table>';
echo "</form></div></div>";
?>
