<?php
  
echo "<form name='vpsa201' action='index.php' method='post'  onSubmit='return checkEditvFields(this)'>";
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="11%" align="center">Código/ID</th>';
echo '<th width="70%" align="left">NOME</th>';
echo '<th width="11%" align="center">SIGLA</th>';
echo '<th width="9%" >AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td width="60" align="center"><font face="verdana" size="1"> [blk_lista_sa201.A2_ID;block=tr]</font> </td>';
echo '<td width="340" align="left"><font face="verdana" size="1" ><span class="AncoraGrid"><a href="?acao=Alt&idsecao=30S&form=29SA&idsub=31&id_p_sa201=[blk_lista_sa201.A2_ID]&nome_p_sa201=[blk_lista_sa201.A2_DESCR]">[blk_lista_sa201.A2_DESCR]</a></span></font></td>';
echo '<td width="60" align="center"><font face="verdana" size="1"> [blk_lista_sa201.A2_SIGLA]</font> </td>';
echo '<td width="50" > <a href="?acao=Alt&idsecao=30S&form=29SA&idsub=31&id_p_sa201=[blk_lista_sa201.A2_ID]&nome_p_sa201=[blk_lista_sa201.A2_DESCR]"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p_cur=[blk_lista_sa201.A2_FILIAL]&id_p_cur=[blk_lista_sa201.A2_ID]&idsecao=[var.idsecao]&form=[var.form]")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '<a href="?acao=Set&idsecao=[var.idsecao]&form=[var.form]&id_p_sa201=[blk_lista_sa201.A2_ID]&idsub=31&id_p_sa201=[blk_lista_sa201.A2_ID]&nome_p_sa201=[blk_lista_sa201.A2_DESCR]"><img src="[var.dir_img]/icons/Ok_16.png" ALT="Seleciona curso" TITLE="Seleciona curso" align="RIGHT"></a>';
echo '</td>';
echo '</tr></tbody>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table><tr><td><form  onSubmit="return checkEditvFields(this)"><input name="voltar" type="button" id="button" onClick="javascript:history.back();" value="Voltar"></td></tr></table></form>';
