<?PHP
  //PEsquisa aluno por id
  $sql_p_sc501 = "SELECT C5.*,
				(SELECT C1_DESCR FROM SC101 WHERE C1_ID = C5.C5_IDATIVIDADE ) AS ATIVIDADE,
				(SELECT C2_DESCR FROM SC201 WHERE C2_ID = C5.C5_IDEVENTO ) AS EVENTO,
				(SELECT C4_DESCR FROM SC401 WHERE C4_ID = C5.C5_IDINSTITUICAO ) AS INSTIT
				FROM SC501 C5 WHERE C5_SEQUENCIA = ".$_REQUEST['id_p_501']." AND C5_FILIAL = '00' ";
  //echo $sql_p_sc501;
?>
