<?php
  
echo "<form name='vpsa201' action='index.php' method='get'  onSubmit='return checkEditvFields(this)'>";
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="12%" align="center">UNIDADE</th>';
echo '<th width="30%" align="center">TURMA</th>';
echo '<th width="30%" align="center">PERÍODO</th>';
echo '<th width="10%" align="center">CURSO</th>';
echo '<th width="10%" align="center">GRADE</th>';
echo '<th width="8%" align="center">AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td width="60" align="center"><font face="verdana" size="1"> [blk_lista_sa401.A4_FILIAL;block=tr]</font> </td>';
echo '<td width="100" align="center"><font face="verdana" size="1"><span class="AncoraGrid"><a href="?acao=Alt&idsecao=17SA&form=17SA&idsub=19&id_p_sa401=[blk_lista_sa401.A4_ID]&idg_p_sa401=[blk_lista_sa401.A4_IDGRADE]&idf_p_sa401=[blk_lista_sa401.A4_FILIAL]">[blk_lista_sa401.A4_ID]</a></span></font></td>';
echo '<td width="100" align="center"><font face="verdana" size="1"> [blk_lista_sa401.AL_DESCR]</font> </td>';
echo '<td width="50" align="center"><font face="verdana" size="1"> [blk_lista_sa401.A4_IDCURSO]</font> </td>';
echo '<td width="50" align="center"><font face="verdana" size="1"> [blk_lista_sa401.A4_IDGRADE]</font> </td>';
echo '<td width="45" > <a href="?acao=Alt&idsecao=17SA&form=17SA&idsub=19&id_p_sa401=[blk_lista_sa401.A4_ID]&idg_p_sa401=[blk_lista_sa401.A4_IDGRADE]&idf_p_sa401=[blk_lista_sa401.A4_FILIAL]"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p_sa401=[blk_lista_sa401.A4_FILIAL]&idd_p_sa401=[blk_lista_sa401.A4_ID]&idsecao=17SA&form=[var.form]")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '<a href="?acao=Set&idsecao=17SA&form=[var.form]&idf_p_sa401=[blk_lista_sa401.A4_FILIAL]&id_p_sa401=[blk_lista_sa401.A4_ID]&idg_p_sa401=[blk_lista_sa401.A4_IDGRADE]&idsub=19"><img src="[var.dir_img]/icons/Ok_16.png" ALT="Seleciona turma" TITLE="Seleciona turma" align="RIGHT"></a>';
echo '</td>';
echo '</tr></tbody>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table><tr><td><form  onSubmit="return checkEditvFields(this)"><input name="voltar" type="button" id="button" onClick="javascript:history.back();" value="Voltar"></td></tr></table></form>';
