<?php
echo "<form name='vpa101' action='index.php' method='post'  onSubmit='return checkEditvFields(this)'>";
echo '<table><tr><td id="textlogin">Resultado da Pesquisa</td></tr></table>';
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="15%" align="left">ID/Código</th>';
echo '<th width="77%" align="left">NOME</th>';
echo '<th width="9%" align="center">AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tr class="dif" onMouseOver=this.className="" onMouseOut=this.className="dif">';
echo '<td width="80" align="center"><font face="verdana" size="1"> [blk_lista_basico.ID;block=tr]</font> </td>';
echo '<td width="300" align="left"><font face="verdana" size="1"><span class="AncoraGrid"><a href="javascript:void(0)" onClick="pegaValorBas(\'C5_idativ\',\'C5_mosativ\',\'[blk_lista_basico.ID]\',\'[blk_lista_basico.DESCR]\')">[blk_lista_basico.DESCR;ope=max:50]</a></span></font></td>';
echo '<td align="center"><a href="javascript:void(0)" onClick="pegaValorBas(\'C5_idativ\',\'C5_mosativ\',\'[blk_lista_basico.ID]\',\'[blk_lista_basico.DESCR]\')"><img src="[var.dir_img]/icons/Download.png" ALT="Seleciona aluno" TITLE="Seleciona aluno" align="CENTER"></a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&cad_p_bas=[var._SESSION.cad_p_bas]&id_p_bas=[var._SESSION.id_p_bas]&nome_p_bas=[var._SESSION.nome_p_bas]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&cad_p_bas=[var._SESSION.cad_p_bas]&id_p_bas=[var._SESSION.id_p_bas]&nome_p_bas=[var._SESSION.nome_p_bas]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&cad_p_bas=[var._SESSION.cad_p_bas]&id_p_bas=[var._SESSION.id_p_bas]&nome_p_bas=[var._SESSION.nome_p_bas]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&cad_p_bas=[var._SESSION.cad_p_bas]&id_p_bas=[var._SESSION.id_p_bas]&nome_p_bas=[var._SESSION.nome_p_bas]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&cad_p_bas=[var._SESSION.cad_p_bas]&id_p_bas=[var._SESSION.id_p_bas]&nome_p_bas=[var._SESSION.nome_p_bas]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table><tr><td><form  onSubmit="return checkEditvFields(this)"><input name="voltar" type="button" id="button" onClick="javascript:history.back();" value="Voltar"></td></tr></table></form>';
