<?php
echo '<div class="container">';
echo "<div id='titcad'>Professor Estágio</div>";  
echo "<div id='titcad2'><label id='nome'>Código/ID Estágio:[var._SESSION.ide_set]</label></div>"; 
echo "<form name='LISESTP' action='index.php' method='get'  onSubmit='return checkEditvFields(this)'>";
echo '<div class="simpleTabs">';
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="6%" align="center">TURNO</th>';
echo '<th width="16%" align="center">DIA SEMANA</th>';
echo '<th width="16%" align="left">ID-DISCIPLINA</th>';
echo '<th width="14%" align="left">ID-PROFESSOR</th>';
echo '<th width="8%" align="center">TURMA</th>';
echo '<th width="7%" align="center">Nº MESES</th>';
echo '<th width="12%" align="left">ID-INSTIT</th>';
echo '<th width="7%" align="left">ID-DEPARTAMENTO</th>';
echo '<th width="6%" align="center">AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td align="center">[blk_lista_se401.E4_TURNO;block=tr]</td>';
echo "<td align='center'><font face='verdana' size='1'><select style='width:100%;' name='C[blk_lista_se401.E3_IDDISC][blk_lista_se401.E4_DIASEMANA][blk_lista_se401.AF_ID][blk_lista_se401.E4_TURNO]S' disabled>" .lista_diasemana()."</select><script>document.LISESTP.C[blk_lista_se401.E3_IDDISC][blk_lista_se401.E4_DIASEMANA][blk_lista_se401.AF_ID][blk_lista_se401.E4_TURNO]S.value = '[blk_lista_se401.E4_DIASEMANA]';</script></font> </td>";
echo '<td align="left"><font face="verdana" size="1">[blk_lista_se401.E3_IDDISC]-[blk_lista_se401.A3_DESCR;ope=max:9]</font></td>';
echo '<td align="left"><font face="verdana" size="1">[blk_lista_se401.AF_ID]-[blk_lista_se401.AF_DESCR;ope=max:7]</font></td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_se401.E3_IDTURMA]</font> </td>';
echo '<td  align="center"><font face="verdana" size="1"> [blk_lista_se401.E3_NMESES]</font> </td>';
echo "<td align='left'><font face='verdana' size='1'>[blk_lista_se401.E3_IDINSTITUTO]-[blk_lista_se401.E1_FANTASIA;ope=max:8]</font> </td>";
echo '<td align="left"><font face="verdana" size="1">[blk_lista_se401.E3_IDDEPTO]-[blk_lista_se401.E2_DESCRICAO;ope=max:9]</font> </td>';
echo '<td> <a href="?acao=Alt&idsecao=30TA&form=30TA&idf_p=[blk_lista_se401.E3_FILIAL]&ide_p=[blk_lista_se401.E3_ID]&idp_p=[blk_lista_se401.AF_ID]&idsub=[var.idsub]&ids_p=[blk_lista_se401.E4_DIASEMANA]"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p=[blk_lista_se401.E3_FILIAL]&ide_p=[blk_lista_se401.E3_ID]&idd_p=[blk_lista_se401.E4_DIASEMANA]&idt_p=[blk_lista_se401.E4_TURNO]&form=[var.form]&idsecao=30TA&idsub=[var.idsub]")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '</td>';
echo '</tr></tbody>';
echo '</table>';
echo "<table width='100%'><tr><td><label id='fieldsetar'>[var.msg]</label></td></tr></table>";
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table>';
echo "<tr><td><form  onSubmit='return checkEditvFields(this)'><input name='voltar' type='button' onClick='javascript:history.back();' value='Voltar' id='button'></td>
<td width='16'><img src='[var.dir_img]/icons/Add_16.png' ALT='Novo cadastro de desconto' TITLE='Novo cadastro de desconto' align='LEFT'></td><td width='183'><a href='?form=30TI&idsub=[var.idsub]'>Novo cadastro</a></td></tr>";
echo '</table>';
echo "</form></div></div>";
