<?php
echo "<form name='vpa101' action='index.php' method='post'  onSubmit='return checkEditvFields(this)'>";
echo '<table><tr><td id="textlogin">Resultado da Pesquisa</td></tr></table>';
echo '<table border="0" width="540" id="alter">';
echo '<thead>';
echo '<tr>';
echo '<td width="80" align="center"><font face="ariel black" size="1">MATRICULA</font></td>';
echo '<td width="340" ><font face="ariel black" size="1">NOME</font></td>';
echo '<td width="80" align="center"><font face="ariel black" size="1">FONE</font></td>';
echo '<td width="40" align="center"><font face="ariel black" size="1">AÇÃO</font></td>';
echo '</tr>';
echo '</thead>';
echo '<tr class="dif" onMouseOver=this.className="" onMouseOut=this.className="dif">';
echo '<td width="80" align="center"><font face="verdana" size="1"> [blk_lista_a101.A1_MATRICULA;block=tr]</font> </td>';
echo '<td width="300"><font face="verdana" size="1"><span class="AncoraGrid"><a href="javascript:void(0)" onClick="pegaValor(\'matalu\',\'IDalu\',\'nomealu\',\'[blk_lista_a101.A1_MATRICULA]\',\'[blk_lista_a101.A1_ID]\',\'[blk_lista_a101.A1_NOME]\')">[blk_lista_a101.A1_NOME]</a></span></font></td>';
echo '<td width="80"><font face="verdana" size="1"> [blk_lista_a101.A1_FONE]</font> </td>';
echo '<td align="center"><a href="javascript:void(0)" onClick="pegaValor(\'matalu\',\'IDalu\',\'nomealu\',\'[blk_lista_a101.A1_MATRICULA]\',\'[blk_lista_a101.A1_ID]\',\'[blk_lista_a101.A1_NOME]\')"><img src="[var.dir_img]/icons/Download.png" ALT="Seleciona aluno" TITLE="Seleciona aluno" align="CENTER"></a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="1" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&[var._SESSION.parte]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]">|&lt;</a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&[var._SESSION.parte]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]">&lt;</a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&[var._SESSION.parte]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&[var._SESSION.parte]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]">&gt;</a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&[var._SESSION.parte]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]">&gt;|</a></td>';
echo '</tr>';
echo '</table>';
echo '<table><tr><td><form  onSubmit="return checkEditvFields(this)"><input name="voltar" type="button" id="button" onClick="javascript:history.back();" value="Voltar"></td></tr></table></form>';
