<?php
echo "<form name='vpa101' action='index.php' method='post'  onSubmit='return checkEditvFields(this)'>";
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="15%" align="left">MATRICULA</th>';
echo '<th width="61%" align="left">NOME</th>';
echo '<th width="16%" align="center">FONE</th>';
echo '<th width="9%" align="center">AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td width="80" align="left"><font face="verdana" size="1"> [blk_lista_a101.A1_MATRICULA;block=tr]</font> </td>';
echo '<td width="300" align="left"><font face="verdana" size="1"><span class="AncoraGrid"><a href="?acao=Alt&idsecao=1SA&form=1SA&ida_p_a101=[blk_lista_a101.A1_ID]&idsub=3&mat_pesq=[blk_lista_a101.A1_MATRICULA]&nome_alu=[blk_lista_a101.A1_NOME]&idacur_p_a101=[var._SESSION.cursopric]">[blk_lista_a101.A1_NOME]</a></span></font></td>';
echo '<td width="80"><font face="verdana" size="1"> [blk_lista_a101.A1_FONE]</font> </td>';
echo '<td width="40" > <a href="?acao=Alt&idsecao=1SA&form=1SA&ida_p_a101=[blk_lista_a101.A1_ID]&idsub=3&mat_pesq=[blk_lista_a101.A1_MATRICULA]&nome_alu=[blk_lista_a101.A1_NOME]&idacur_p_a101=[var._SESSION.cursopric]"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p_a101=[blk_lista_a101.A1_FILIAL]&ida_p_a101=[blk_lista_a101.A1_ID]&idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '<a href="?acao=Set&idsecao=[var.idsecao]&form=[var.form]&ida_p_a101=[blk_lista_a101.A1_ID]&idsub=3&mat_pesq=[blk_lista_a101.A1_MATRICULA]&nome_alu=[blk_lista_a101.A1_NOME]&idacur_p_a101=[var._SESSION.cursopric]"><img src="[var.dir_img]/icons/Ok_16.png" ALT="Seleciona aluno" TITLE="Seleciona aluno" align="RIGHT"></a>';
echo '</td>';
echo '</tr></tbody>';
echo '</table>';
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?idsecao=[var.idsecao]&form=[var.form]&[var._SESSION.parte]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table><tr><td><form  onSubmit="return checkEditvFields(this)"><input name="voltar" type="button" id="button" onClick="javascript:history.back();" value="Voltar"></td></tr></table></form>';
