<?php
echo '<div class="container">';
echo "<div id='titcad'>Cadastrar Estágio</div>";  
 
echo "<form name='LISEST' action='index.php' method='get'  onSubmit='return checkEditvFields(this)'>";
echo '<div class="simpleTabs">';
echo '<table border="0" id="box-table-b">';
echo '<thead>';
echo '<tr>';
echo '<th width="4%" align="center">ID</th>';
echo '<th width="19%" align="left">ID-DISCIPLINA</th>';
echo '<th width="10%" align="center">INÍCIO</th>';
echo '<th width="10%" align="center">TERMINO</th>';
echo '<th width="4%" align="center">DIAS</th>';
echo '<th width="8%" align="center">TURMA</th>';
echo '<th width="7%" align="center">Nº MESES</th>';
echo '<th width="14%" align="left">ID-INSTIT</th>';
echo '<th width="7%" align="left">ID-DEPARTAMENTO</th>';
echo '<th width="8%" align="center">AÇÃO</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody><tr>';
echo '<td align="center"><font face="verdana" size="1">[blk_lista_se301.E3_ID;block=tr]</font></td>';
echo '<td align="left"><font face="verdana" size="1">[blk_lista_se301.E3_IDDISC]-[blk_lista_se301.A3_DESCR;ope=max:12]</font></td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_se301.E3_DTINICIO;frm=\'dd/mm/yyyy\']</font> </td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_se301.E3_DTFIM;frm=\'dd/mm/yyyy\']</font> </td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_se301.E3_DIAS]</font> </td>';
echo '<td align="center"><font face="verdana" size="1"> [blk_lista_se301.E3_IDTURMA]</font> </td>';
echo '<td  align="center"><font face="verdana" size="1"> [blk_lista_se301.E3_NMESES]</font> </td>';
echo "<td align='left'><font face='verdana' size='1'>[blk_lista_se301.E3_IDINSTITUTO]-[blk_lista_se301.E1_FANTASIA;ope=max:10]</font> </td>";
echo '<td align="left"><font face="verdana" size="1">[blk_lista_se301.E3_IDDEPTO]-[blk_lista_se301.E2_DESCRICAO;ope=max:9]</font> </td>';
echo '<td> <a href="?acao=Alt&idsecao=59SA&form=59SA&idsub=59&ide_p=[blk_lista_se301.E3_ID]&n=3&no=Visualizar/Editar"><img src="[var.dir_img]/icons/alterar_registro.gif" ALT="Alterar" TITLE="Alterar" align="LEFT"></a>';
echo '<a href="?acao=Alt&idsecao=59SA&form=59SA&idsub=59&ide_p=[blk_lista_se301.E3_ID]&n=3&no=Visualizar/Editar"><img src="[var.dir_img]/icons/localizar.gif" TITLE="Visualizar" align="LEFT"></a>';
echo '<a href=\'javascript:confirmaExclusao("?acao=Del&idf_p=[blk_lista_se301.E3_FILIAL]&ide_p=[blk_lista_se301.E3_ID]&form=[var.form]&idsecao=59SA&idsub=59")\'><img src="[var.dir_img]/icons/Excluir.gif" ALT="Deletar" TITLE="Deletar" align="LEFT"></a>';
echo '</td>';
echo '</tr></tbody>';
echo '</table>';
echo "<table width='100%'><tr><td><label id='fieldsetar'>[var.msg]</label></td></tr></table>";
echo '<div align="center"><br>';
echo 'Numero de registros: [var.RecCnt]<br>10 por pagina.';
echo '<br>';
echo '</div>';
echo '<table border="0" align="center" cellpadding="2" cellspacing="0">';
echo '<tr align="center">';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.first;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pri]" TITLE="Primeira pagina"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.prev;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ant]" TITLE="Anterior"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.page;block=td;navsize=3;navpos=centred]">[nv.page]</a></td>';
echo '<td width="16" bgcolor="#C4E1E1"><strong>[nv.page;block=td;currpage]</strong></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.next;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_pro]"  TITLE="Proxima"></a></td>';
echo '<td width="16"><a href="[var..script_name]?form=[var.form]&PageNum=[nv.last;endpoint;magnet=a;mtype=m+m]"><img src="[var.dir_img]/icons/[var.pag_ult]"  TITLE="Ultima pagina"></a></td>';
echo '</tr>';
echo '</table>';
echo '<table>';
echo "<tr><td><form  onSubmit='return checkEditvFields(this)'><input name='voltar' type='button' onClick='javascript:history.back();' value='Voltar' id='button'></td>
<td width='16'><img src='[var.dir_img]/icons/Add_16.png' ALT='Novo cadastro de desconto' TITLE='Novo cadastro de desconto' align='LEFT'></td><td width='183'><a href='?form=59SI'>Novo cadastro</a></td></tr>";
echo '</table>';
echo "</form></div></div>";
